### ISSUE TITLE
branch Webpack2: module parse failed

### ISSUE THREAD

**Issue by Falieson** [jcoreio/crater#129] opened 2017-03-25 23:08 UTC
Hi again jcoreio, 
Started off attempting the webpack2 branch which seems to be broken, the master branch seems to be solid though. I'm looking forward to trying out this repo. 
~Falieson

=== Steps To Reproduce
$ `git checkout webpack2`
$ `npm i && npm start`

=== Error 
~/Demos/crater (webpack2)
```WARNING in webpack: Using NoErrorsPlugin is deprecated.
Use NoEmitOnErrorsPlugin instead.


ERROR in ./~/meteor-imports-webpack-plugin/meteor-config.json
Module parse failed: /Users/florian/Code/Education/Demos/crater/node_modules/json-string-loader/index.js?json={"meteorProgramsFolder":"/Users/florian/Code/Education/Demos/crater/build/meteor/bundle/programs","injectMeteorRuntimeConfig":false,"exclude":["autoupdate","global-imports","hot-code-push","reload","ecmascript"]}!/Users/florian/Code/Education/Demos/crater/node_modules/meteor-imports-webpack-plugin/meteor-config.json Unexpected token (1:114)
You may need an appropriate loader to handle this file type.
| module.exports = {"meteorProgramsFolder":"/Users/florian/Code/Education/Demos/crater/build/meteor/bundle/programs"
 @ ./~/meteor-imports-webpack-plugin/meteor-imports.js 2:13-44
 @ ./src/client/index.js
 @ multi ./src/client/index.js react-hot-loader/patch webpack-hot-middleware/client
^C
```

**Comment by jedwards1211** [comment] 2017-03-30 18:13
Sorry for the delay.  This is a dupe of https://github.com/luisherranz/meteor-imports-webpack-plugin/issues/13 (crater relies on that library).  I have a workaround I'll apply for the time being though

**Comment by jedwards1211** [comment] 2017-03-30 18:43
@Falieson everything should be fixed in [this commit](https://github.com/jcoreio/crater/pull/116/commits/83371c245941b96ca4ff6f7b8ec89b06c93383fe), I'm just waiting for it to pass...

**Comment by jedwards1211** [comment] 2017-03-30 20:47
@Falieson correction, now I'm fixing in the fix/webpack2/meteor-imports-webpack-plugin branch, and it's no longer a workaround but a real fix

**Comment by jedwards1211** [comment] 2017-03-30 22:28
okay, the webpack2 branch is now fixed

**Closed by jedwards1211** 2017-03-30 22:28 UTC

**Comment by Falieson** [comment] 2017-04-06 01:36
Thanks! Will try it out soon.
